{% set version=load_setup_py_data().get('version') %}

package:
  name: clearup
  version: "1.1.3"

source:
  git_url: https://github.com/AstraZeneca-NGS/ClearUp
  git_rev: master

build:
  number: 8

requirements:
  build:
    - python
    - numpy
    - ngs_utils
    - six
    - flask
    - flask-script
    - flask-sqlalchemy
    - flask-socketio
  run:
    - python
    - numpy
    - ngs_utils
    - six
    - sambamba
    - bedtools >=2.25
    - bedops
    - pybedtools
    - click
    - sqlalchemy
    - biopython
    - gevent
    - gevent-websocket
    - pyvcf
    - cyvcf2
    - flask
    - flask-script
    - flask-sqlalchemy
    - flask-socketio
    - prank
    - nose
    - genomepy

test:
  imports:
   - clearup

about:
  home: https://github.com/AstraZeneca-NGS/ClearUp
  license: GNU General Public License v3 (GPLv3)
  summary: 'Sample identity validation and mix-up check'
  license_family: GPL3

